import { ThemeConfig, BlockTypeConfig } from '../types';

export const BLOCK_TIERS: Record<number, BlockTypeConfig> = {
  1: {
    tier: 1,
    id: 'temp',
    name: 'Temporary Cache / Log Buffer',
    shortName: 'TEMP/CACHE',
    basePoints: 1,
    char: '░',
    description: 'Volatile scratchpad chunks & temporary stream cache.',
    colorKey: 'tier1',
    targetZone: 'Track 4: Outer Perimeter',
  },
  2: {
    tier: 2,
    id: 'user',
    name: 'User Data / Media Clusters',
    shortName: 'USER_DATA',
    basePoints: 2,
    char: '▒',
    description: 'Documents, media packages, and local asset blobs.',
    colorKey: 'tier2',
    targetZone: 'Track 3: Middle Band',
  },
  3: {
    tier: 3,
    id: 'apps',
    name: 'Application Executables & DLLs',
    shortName: 'APP_EXEC',
    basePoints: 3,
    char: '▓',
    description: 'Binary runtimes, shared libraries, and native modules.',
    colorKey: 'tier3',
    targetZone: 'Track 2: Inner-Mid Band',
  },
  4: {
    tier: 4,
    id: 'system',
    name: 'System State & Registry Tree',
    shortName: 'SYS_REG',
    basePoints: 4,
    char: '█',
    description: 'Kernel state trees, hardware tables, and system maps.',
    colorKey: 'tier4',
    targetZone: 'Track 1: System Track',
  },
  5: {
    tier: 5,
    id: 'kernel',
    name: 'Compressed Kernel Archive',
    shortName: 'KERN_ARCH',
    basePoints: 5,
    char: '█',
    description: 'High-density encrypted core payload & boot manifests.',
    colorKey: 'tier5',
    targetZone: 'Track 0: Fast Boot Sector',
  },
};

export const THEMES: Record<string, ThemeConfig> = {
  btop: {
    id: 'btop',
    name: 'btop Neo-Dark',
    bg: '#0a0d14',
    cardBg: '#0f141f',
    cardBorder: '#1e293b',
    headerBg: '#131b2c',
    accent: '#38bdf8',
    accentHover: '#0ea5e9',
    textPrimary: '#f1f5f9',
    textMuted: '#94a3b8',
    textDim: '#475569',
    tierColors: {
      1: '#64748b', // Slate
      2: '#10b981', // Emerald
      3: '#06b6d4', // Cyan
      4: '#f59e0b', // Amber
      5: '#ec4899', // Hot Pink
      free: '#1e293b',
      corrupt: '#ef4444',
      head: '#ffffff',
      sorted: '#22c55e',
    },
  },
  win98: {
    id: 'win98',
    name: 'Win98 Norton Classic',
    bg: '#000000',
    cardBg: '#000080',
    cardBorder: '#0000aa',
    headerBg: '#0000aa',
    accent: '#ffff00',
    accentHover: '#facc15',
    textPrimary: '#ffffff',
    textMuted: '#a0a0ff',
    textDim: '#5050aa',
    tierColors: {
      1: '#c0c0c0', // White/Silver
      2: '#00ff00', // Green
      3: '#00ffff', // Cyan
      4: '#ffff00', // Yellow
      5: '#ff0000', // Red
      free: '#000033',
      corrupt: '#ff0055',
      head: '#ffffff',
      sorted: '#0055ff',
    },
  },
  phosphor: {
    id: 'phosphor',
    name: 'CRT Phosphor Green',
    bg: '#030a03',
    cardBg: '#061306',
    cardBorder: '#143814',
    headerBg: '#0a220a',
    accent: '#22c55e',
    accentHover: '#4ade80',
    textPrimary: '#86efac',
    textMuted: '#4ade80',
    textDim: '#166534',
    tierColors: {
      1: '#14532d',
      2: '#16a34a',
      3: '#22c55e',
      4: '#4ade80',
      5: '#bbf7d0',
      free: '#071d07',
      corrupt: '#dc2626',
      head: '#ffffff',
      sorted: '#22c55e',
    },
  },
  amber: {
    id: 'amber',
    name: 'VT220 Amber',
    bg: '#0a0702',
    cardBg: '#170e03',
    cardBorder: '#382207',
    headerBg: '#261605',
    accent: '#f59e0b',
    accentHover: '#fbbf24',
    textPrimary: '#fed7aa',
    textMuted: '#fb923c',
    textDim: '#7c2d12',
    tierColors: {
      1: '#78350f',
      2: '#b45309',
      3: '#d97706',
      4: '#f59e0b',
      5: '#fde68a',
      free: '#201103',
      corrupt: '#ef4444',
      head: '#ffffff',
      sorted: '#f59e0b',
    },
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk 2077',
    bg: '#090514',
    cardBg: '#120b24',
    cardBorder: '#311b58',
    headerBg: '#1e0e3b',
    accent: '#f43f5e',
    accentHover: '#fb7185',
    textPrimary: '#fce7f3',
    textMuted: '#c084fc',
    textDim: '#581c87',
    tierColors: {
      1: '#701a75',
      2: '#06b6d4',
      3: '#8b5cf6',
      4: '#facc15',
      5: '#f43f5e',
      free: '#180a30',
      corrupt: '#ff003c',
      head: '#ffffff',
      sorted: '#10b981',
    },
  },
};
